// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7zrLq9YPzEWS2GihzYBggqiF4H_M3T4',
    appId: '1:772038159363:web:a04db7717608c620cdb236',
    messagingSenderId: '772038159363',
    projectId: 'don-troc-app-3b071',
    authDomain: 'don-troc-app-3b071.firebaseapp.com',
    storageBucket: 'don-troc-app-3b071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwXWbxiBkD5896cXZS18r4LsFFBetbQM',
    appId: '1:772038159363:android:d10f3309e758144ecdb236',
    messagingSenderId: '772038159363',
    projectId: 'don-troc-app-3b071',
    storageBucket: 'don-troc-app-3b071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEpSQE9sDeEzbAhAnK8lCccghcim3gqvw',
    appId: '1:772038159363:ios:6332f65b5b1887f7cdb236',
    messagingSenderId: '772038159363',
    projectId: 'don-troc-app-3b071',
    storageBucket: 'don-troc-app-3b071.firebasestorage.app',
    iosBundleId: 'com.example.donTro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEpSQE9sDeEzbAhAnK8lCccghcim3gqvw',
    appId: '1:772038159363:ios:6332f65b5b1887f7cdb236',
    messagingSenderId: '772038159363',
    projectId: 'don-troc-app-3b071',
    storageBucket: 'don-troc-app-3b071.firebasestorage.app',
    iosBundleId: 'com.example.donTro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7zrLq9YPzEWS2GihzYBggqiF4H_M3T4',
    appId: '1:772038159363:web:b66d93b9670323c7cdb236',
    messagingSenderId: '772038159363',
    projectId: 'don-troc-app-3b071',
    authDomain: 'don-troc-app-3b071.firebaseapp.com',
    storageBucket: 'don-troc-app-3b071.firebasestorage.app',
  );

}